language: go

go:
  - 1.7
  - 1.8
  - 1.9

install:
  - go get github.com/tsdtsdtsd/gobbs
  - go get -v .
  - go get -v github.com/golang/lint/golint 

script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint ./...
  - go test -v -race ./...